name: proximize
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  #Default set of icon assets used by Flutter cupertino widgets
  cupertino_icons: ^1.0.2
  #Scrollable images slider.
  carousel_slider: ^4.2.1
  #Indicators for scrollable widgets
  smooth_page_indicator: ^1.1.0
  #Draw SVG images
  flutter_svg: ^2.0.9
  #For app navigation
  go_router: ^13.0.1
  #For responsive design
  flutter_screenutil: ^5.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

